### ISSUE TITLE
gh-pages not working as advitised

### ISSUE THREAD

**Issue by dotnetCarpenter** [dionyziz/stream.js-website#1]
Hi @dionyziz. I tried to move the website. I even fix the button gradient thingy in IE11. I followed [the guide](https://help.github.com/articles/creating-project-pages-manually/) but no dice. Maybe because I'm a contributor - who knows. I wrote github support and will let you know here, when they respond,

**Comment by dotnetCarpenter** [comment]
Response from github:

> The page build failed with the following error:
> 
> The submodule `stream` was not properly initialized with a `.gitmodules` file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.
> 
> If you have any questions you can contact us by replying to this email.

@dionyziz can you commit the `.gitmodules` file?

**Comment by dotnetCarpenter** [comment]
I figure that the `stream` folder is stream.js. Should be fixed

**Comment by dotnetCarpenter** [comment]
Website is up :tada:  http://dionyziz.github.io/stream.js-website/
You'll need to point streamjs.org to the new home but read this first: https://help.github.com/articles/about-custom-domains-for-github-pages-sites/

**Comment by dionyziz** [comment]
Done, looking good! :)

**Comment by dotnetCarpenter** [comment]
nice. But it seems that the naked domain is broken. That is www.streamjs.org works but streamjs.org does not. This breaks the reference to stream.js on the site. I will fix that ASAP. But you should make a dns redirect to www from the naked domain.

**Comment by dionyziz** [comment]
I fixed it. Can you check if it works now? (Please allow for some time for DNS propagation)

**Comment by dotnetCarpenter** [comment]
@dionyziz yep - it works!
