### ISSUE TITLE
Undocumented methods

### ISSUE THREAD

**Issue by GeorgeGkas** [dionyziz/stream.js-website#4]
After many contributions, new methods were implemented without to be documented on the official page.  Bellow I provide a brief list of such methods:

**Instance methods**
- `Stream.prototype.append()`
- `Stream.prototype.zip()`
- `Stream.prototype.concatmap()`
- `Stream.prototype.reduce()`
- `Stream.prototype.sum()`
- `Stream.prototype.force()`
- `Stream.prototype.takeWhile()`
- `Stream.prototype.drop()`
- `Stream.prototype.dropWhile()`
- `Stream.prototype.member()`

**Static methods**
- `Stream.continually()`
- `Stream.continuallyEager()`
- `Stream.repeat()`
- `Stream.makeOnes()`
- `Stream.makeNaturalNumbers()`
- `Stream.make()`
- `Stream.fromArray()`
- `Stream.range()`
- `Stream.equals()`
- `Stream.iterate()`
- `Stream.iterateEager()`
- `Stream.cycle()`

**Comment by dotnetCarpenter** [comment]
@GeorgeGkas you are right! We actually meant to to do that [2 years ago](https://github.com/dionyziz/stream.js/issues/25) but never found the time. I've been meaning to ask you, since your great PR, if you would be interested in maintaining stream.js? If yes, then I'll send you an invite. @dionyziz made a good description of many of the methods, that we could build upon.

**Comment by GeorgeGkas** [comment]
@dotnetCarpenter sure I would like to. Check issue #5 as well. I believe that those two issues are related to each other. Also, notice that the issue you are referring to does not contain the descriptions of all the above methods.

**Comment by dotnetCarpenter** [comment]
Yes I saw #5. You're right that #25 in the stream.js repo doesn't cover everything but it's a good start. I'll see if I can get your invited as a collaborator on both repos.

**Comment by GeorgeGkas** [comment]
@dotnetCarpenter I have already started working on the new website. I would like to participate as a collaborator. Would you mind to add me to both projects, please? :+1:

**Comment by GeorgeGkas** [comment]
@dotnetCarpenter I just accepted the invitation request from @dionyziz.
