### ISSUE TITLE
Add Travis CI support for the project

### ISSUE THREAD

**Issue by GeorgeGkas** [dionyziz/stream.js-website#8]
To be able to generate the website, we added a Travis CI job that automatically keeps tracking the master branch and updates the gh-pages, as described in commit c6297b9cad1c65fdb470a9cea2378d96779db200. Right now this repo is not being watched by Travis CI because only the owner has the appropriate priveledges to do so. Please add this repository to Travis CI.

**Comment by dionyziz** [comment]
Done.
